name: shadow_garden
description: "A new Flutter project."
publish_to: 'none'
version: 1.10.7

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  audio_video_progress_bar: ^2.0.1
  just_audio: ^0.10.4
  just_audio_background: ^0.0.1-beta.11
  rxdart: ^0.28.0
  lottie: ^3.0.0
  marquee: ^2.2.3
  on_audio_query_forked: ^2.9.1
  numberpicker: ^2.1.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5
  intl: ^0.20.2
  file_picker: ^10.1.9
  drift: ^2.26.1
  drift_flutter: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  drift_dev: ^2.26.1
  rename: ^3.1.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/visualizers/
    - assets/i18n/
